on:
  workflow_dispatch:

jobs:
  # الـ Job الأولى: بتشتغل على الـ VM العادي
  hybrid_job:
    runs-on: ubuntu-latest
    steps:
      - name: runs on ubuntu vm
        run: echo "this is ubuntu vm"

      # الطريقة دي صحيحة لتشغيل سطر واحد جوه كونتينر سريع
      - name: runs on alpine container
        uses: docker://alpine:3.12
        with:
          entrypoint: /bin/sh
          args: -c "echo 'this is alpine container'"

      - name: BACK to ubuntu vm
        run: echo "back to ubuntu vm"

  # الـ Job الثانية: مخصصة بالكامل للـ Node container
  node_job:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - run: node --version
      - run: echo "this is node container"
