on: 
 workflow_dispatch: 
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  say-hello-2:
    runs-on: ubuntu-latest
    steps:
      - run: print("hello world from python script")
        shell: python
  ls-the-files:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
    needs:
      - say-hello
      - say-hello-2
   
